/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueViewsRouteImport } from './routes/queue-views'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueViewsNameRouteImport } from './routes/queue-views.$name'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const QueueViewsRoute = QueueViewsRouteImport.update({
  id: '/queue-views',
  path: '/queue-views',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueViewsNameRoute = QueueViewsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => QueueViewsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRouteWithChildren
  '/queue-views': typeof QueueViewsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queue-views/$name': typeof QueueViewsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRouteWithChildren
  '/queue-views': typeof QueueViewsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queue-views/$name': typeof QueueViewsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRouteWithChildren
  '/queue-views': typeof QueueViewsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queue-views/$name': typeof QueueViewsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/jobs'
    | '/queue-views'
    | '/jobs/$jobId'
    | '/queue-views/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/jobs'
    | '/queue-views'
    | '/jobs/$jobId'
    | '/queue-views/$name'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/jobs'
    | '/queue-views'
    | '/jobs/$jobId'
    | '/queue-views/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  JobsRoute: typeof JobsRouteWithChildren
  QueueViewsRoute: typeof QueueViewsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue-views': {
      id: '/queue-views'
      path: '/queue-views'
      fullPath: '/queue-views'
      preLoaderRoute: typeof QueueViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-views/$name': {
      id: '/queue-views/$name'
      path: '/$name'
      fullPath: '/queue-views/$name'
      preLoaderRoute: typeof QueueViewsNameRouteImport
      parentRoute: typeof QueueViewsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface QueueViewsRouteChildren {
  QueueViewsNameRoute: typeof QueueViewsNameRoute
}

const QueueViewsRouteChildren: QueueViewsRouteChildren = {
  QueueViewsNameRoute: QueueViewsNameRoute,
}

const QueueViewsRouteWithChildren = QueueViewsRoute._addFileChildren(
  QueueViewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  JobsRoute: JobsRouteWithChildren,
  QueueViewsRoute: QueueViewsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
